[package]
name = "nightcycle/maid"
description = "Maid class with exported type"
version = "2.0.0"
authors = ["Quenty", "Nightcycle"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
