[package]
name = "nightcycle/package"
description = "A package!"
version = "1.0.0"
authors = ["Quenty", "CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
